from rest_framework import serializers
from .models import (
    MuscleGroup, Equipment, BaseExercise, Exercise, Workout, WorkoutExercise,
    MealEntry, DailyLog
)
from datetime import date
from django.contrib.auth.models import User


# --- Basic Model Serializers ---

class MuscleGroupSerializer(serializers.ModelSerializer):
    """Convert MuscleGroup objects to/from JSON"""
    class Meta:
        model = MuscleGroup
        fields = ['id', 'name']


class EquipmentSerializer(serializers.ModelSerializer):
    """Convert Equipment objects to/from JSON"""
    class Meta:
        model = Equipment
        fields = ['id', 'name']


class ExerciseSerializer(serializers.ModelSerializer):
    """Convert Exercise objects to/from JSON with related data"""
    primary_muscle_group_name = serializers.CharField(source='primary_muscle_group.name', read_only=True)
    equipment_name = serializers.CharField(source='equipment.name', read_only=True)
    secondary_muscle_groups_names = serializers.SerializerMethodField()

    class Meta:
        model = Exercise
        fields = [
            'id', 'name', 'primary_muscle_group', 'primary_muscle_group_name',
            'secondary_muscle_groups', 'secondary_muscle_groups_names',
            'equipment', 'equipment_name'
        ]

    def get_secondary_muscle_groups_names(self, obj):
        """Get list of secondary muscle group names"""
        return [mg.name for mg in obj.secondary_muscle_groups.all()]


class WorkoutExerciseSerializer(serializers.ModelSerializer):
    """Convert WorkoutExercise junction table to/from JSON"""
    exercise_name = serializers.CharField(source='exercise.name', read_only=True)
    primary_muscle_group = serializers.CharField(source='exercise.primary_muscle_group.name', read_only=True)
    equipment = serializers.CharField(source='exercise.equipment.name', read_only=True)

    class Meta:
        model = WorkoutExercise
        fields = [
            'id', 'exercise', 'exercise_name', 'primary_muscle_group', 'equipment',
            'sets', 'reps', 'weight', 'rest_seconds', 'notes', 'order'
        ]


class WorkoutSerializer(serializers.ModelSerializer):
    """Convert Workout objects to/from JSON with all exercises included"""
    workout_exercises = WorkoutExerciseSerializer(source='workoutexercise_set', many=True, read_only=True)
    exercise_count = serializers.SerializerMethodField()

    class Meta:
        model = Workout
        fields = [
            'id', 'name', 'date', 'notes', 'created_at',
            'workout_exercises', 'exercise_count'
        ]

    def get_exercise_count(self, obj):
        """Count how many exercises are in this workout"""
        return obj.workoutexercise_set.count()


# --- AI Workout Creation Serializer ---

class ExerciseInputSerializer(serializers.Serializer):
    """Serializer for each AI-generated exercise"""
    name = serializers.CharField()
    sets = serializers.IntegerField(required=False, min_value=1)
    reps = serializers.IntegerField(required=False, min_value=1)
    weight = serializers.FloatField(required=False, allow_null=True)
    muscle_group = serializers.CharField(required=False, allow_blank=True)
    equipment = serializers.CharField(required=False, allow_blank=True)
    rest_seconds = serializers.IntegerField(required=False, allow_null=True)
    notes = serializers.CharField(required=False, allow_blank=True, allow_null=True)


class AIWorkoutCreateSerializer(serializers.Serializer):
    """
    Handles data coming from n8n/AI to create workouts safely.
    Allows blank notes, auto-fills defaults, and creates proper Exercise links.
    """
    user_id = serializers.IntegerField(default=1)
    workout_name = serializers.CharField(max_length=200)
    workout_date = serializers.DateField(required=False, default=date.today())
    notes = serializers.CharField(required=False, allow_blank=True, allow_null=True)
    exercises = ExerciseInputSerializer(many=True)

    def validate_exercises(self, value):
        """Apply defaults and clean up data"""
        for ex in value:
            ex.setdefault('sets', 3)
            ex.setdefault('reps', 10)
            if ex.get('notes', "") == "":
                ex['notes'] = None
            if ex.get('muscle_group', "") == "":
                ex['muscle_group'] = "General"
            if ex.get('equipment', "") == "":
                ex['equipment'] = "Bodyweight"
        return value

    def create(self, validated_data):
        """Create the workout and related exercises"""

        user_id = validated_data.get('user_id', 1)
        workout_name = validated_data['workout_name']
        workout_date = validated_data.get('workout_date')
        notes = validated_data.get('notes', 'Generated by AI assistant')
        exercises_data = validated_data['exercises']

        # get user
        try:
            user = User.objects.get(id=user_id)
        except User.DoesNotExist:
            user = User.objects.first()

        # create the workout
        workout = Workout.objects.create(
            user=user,
            name=workout_name,
            date=workout_date,
            notes=notes
        )

        # create or link exercises properly
        for order, ex in enumerate(exercises_data):
            mg = self._get_or_create_muscle_group(ex.get('muscle_group', 'General'))
            eq = self._get_or_create_equipment(ex.get('equipment', 'Bodyweight'))

            # base exercise represents generic movement
            base_ex, _ = BaseExercise.objects.get_or_create(
                name=ex['name'],
                defaults={'primary_muscle_group': mg}
            )

            # leaf Exercise is instance with specific equipment
            exercise, _ = Exercise.objects.get_or_create(
                name=ex['name'],
                defaults={'base_exercise': base_ex, 'equipment': eq}
            )

            WorkoutExercise.objects.create(
                user=user,
                name=ex['name'],
                workout=workout,
                exercise=exercise,
                sets=int(ex.get('sets', 3)),
                reps=int(ex.get('reps', 10)),
                weight=float(ex['weight']) if ex.get('weight') is not None else None,
                rest_seconds=int(ex['rest_seconds']) if ex.get('rest_seconds') else None,
                notes=ex.get('notes') or "",
                order=order
            )
        return workout

    def _get_or_create_muscle_group(self, name):
        mg, _ = MuscleGroup.objects.get_or_create(name=name)
        return mg

    def _get_or_create_equipment(self, name):
        eq, _ = Equipment.objects.get_or_create(name=name)
        return eq


# --- Meal and Daily Log Serializers ---

class MealEntrySerializer(serializers.ModelSerializer):
    """Convert MealEntry objects to/from JSON"""
    class Meta:
        model = MealEntry
        fields = [
            'id', 'name', 'calories', 'protein', 'carbs', 'fats',
            'date', 'created_at'
        ]

class DailyLogSerializer(serializers.ModelSerializer):
    """Convert DailyLog objects to/from JSON with related data"""
    workouts = WorkoutSerializer(many=True, read_only=True)
    meals = MealEntrySerializer(many=True, read_only=True)

    class Meta:
        model = DailyLog
        fields = [
            'id', 'date', 'workouts', 'meals',
            'total_calories', 'total_protein', 'total_carbs', 'total_fats'
        ]

class AIMealCreateSerializer(serializers.Serializer):
    user_id = serializers.IntegerField(default=1)
    meal_name = serializers.CharField(max_length=200)
    calories = serializers.FloatField(required=False)
    protein = serializers.FloatField(required=False)
    carbs = serializers.FloatField(required=False)
    fats = serializers.FloatField(required=False)
    meal_date = serializers.DateField(required=False, default=date.today())
    notes = serializers.CharField(required=False, allow_blank=True)

    def create(self, validated_data):
        user_id = validated_data.get('user_id', 1)
        user = User.objects.get(id=user_id)
        meal_date = validated_data.get('meal_date') or date.today()

        return MealEntry.objects.create(
            user=user,
            name=validated_data.get('meal_name'),
            calories=validated_data.get('calories') or 0,
            protein=validated_data.get('protein') or 0,
            carbs=validated_data.get('carbs') or 0,
            fats=validated_data.get('fats') or 0,
            date=meal_date,
        )
    
    