# Generated by Django 5.2.7 on 2025-10-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='rest_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
